出力ファイル検証

diff --git a/.github/workflows/build-doc.yml b/.github/workflows/build-doc.yml
--- a/.github/workflows/build-doc.yml
+++ b/.github/workflows/build-doc.yml
@@ -1,4 +1,4 @@
-name: Build documentation
+name: Build and Deploy Documentation
 
 on:
   push:
@@ -7,14 +7,13 @@ on:
 
 permissions:
   id-token: write
-  contents: read
   pages: write
 
 env:
   INSTANCE: 'Writerside/v'
   ARTIFACT: 'webHelpV2-all.zip'
   DOCKER_VERSION: '241.18775'
-  ALGOLIA_ARTIFACT: 'algolia-indexes-V2.zip'
+  ALGOLIA_ARTIFACT: 'algolia-indexes-V.zip'
   ALGOLIA_APP_NAME: 'FJLBFRYT23'
   ALGOLIA_INDEX_NAME: 'VultureEcho'
   ALGOLIA_KEY: '${{ secrets.ALGOLIA_KEY }}'
@@ -36,9 +35,15 @@ jobs:
           instance: ${{ env.INSTANCE }}
           artifact: ${{ env.ARTIFACT }}
           docker-version: ${{ env.DOCKER_VERSION }}
-        env:
-          DOCKER_BUILDKIT: 1
-          COMPOSE_DOCKER_CLI_BUILD: 1
+
+      - name: Verify artifact generation
+        run: |
+          echo "Checking if necessary artifacts are generated..."
+          ls -l artifacts/
+          test -e artifacts/${{ env.ARTIFACT }} && echo "${{ env.ARTIFACT }} exists" || (echo "Error: ${{ env.ARTIFACT }} not found" && exit 1)
+          test -e artifacts/report.json && echo "report.json exists" || (echo "Error: report.json not found" && exit 1)
+          test -e artifacts/report.html && echo "report.html exists" || (echo "Error: report.html not found" && exit 1)
+          test -e artifacts/${{ env.ALGOLIA_ARTIFACT }} && echo "${{ env.ALGOLIA_ARTIFACT }} exists" || (echo "Error: ${{ env.ALGOLIA_ARTIFACT }} not found" && exit 1)
 
       - name: Save artifact with build results
         uses: actions/upload-artifact@v4
@@ -47,6 +52,7 @@ jobs:
           path: |
             artifacts/${{ env.ARTIFACT }}
             artifacts/report.json
+            artifacts/report.html
             artifacts/${{ env.ALGOLIA_ARTIFACT }}
           retention-days: 7
 
@@ -102,16 +108,18 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: docs
+
       - name: Unzip Algolia artifact
         run: |
           unzip -O UTF-8 -qq 'artifacts/${{ env.ALGOLIA_ARTIFACT }}' -d algolia-indexes
-      - name: Publish Algolia Indexes
+
+      - name: Upload indexes to Algolia
         run: |
-          env algolia-key='${{env.ALGOLIA_KEY}}' java -jar /opt/builder/help-publication-agent.jar \
+          env algolia-key='${{ env.ALGOLIA_KEY }}' java -jar /opt/builder/help-publication-agent.jar \
           update-index \
-          --application-name '${{env.ALGOLIA_APP_NAME}}' \
-          --index-name '${{env.ALGOLIA_INDEX_NAME}}' \
-          --product '${{env.CONFIG_JSON_PRODUCT}}' \
-          --version '${{env.CONFIG_JSON_VERSION}}' \
+          --application-name '${{ env.ALGOLIA_APP_NAME }}' \
+          --index-name '${{ env.ALGOLIA_INDEX_NAME }}' \
+          --product '${{ env.CONFIG_JSON_PRODUCT }}' \
+          --version '${{ env.CONFIG_JSON_VERSION }}' \
           --index-directory algolia-indexes/ \
           2>&1 | tee algolia-update-index-log.txt
